name: Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MkDocs
        run: pip install mkdocs-material
      - name: Build docs
        run: mkdocs build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          token: ${{ secrets.GH_TOKEN }}
          git-config-name: ${{ secrets.GH_USERNAME }}
          git-config-email: ${{ secrets.GH_EMAIL }}

