name: Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CHANGELOG.md'
  workflow_dispatch:
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install MkDocs
        run: pip install mkdocs==1.5.3 mkdocs-material==9.5.10
      - name: Copy changelog
        run: |
          cp CHANGELOG.md docs/changelog.md
      - name: Build docs
        run: mkdocs build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          token: ${{ secrets.GH_BOT_TOKEN }}
          git-config-name: ${{ vars.GH_BOT_NAME }}
          git-config-email: ${{ vars.GH_BOT_EMAIL }}

